name: CI
on:
  push:
env:
  FORCE_COLOR: "3"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
